import { createContext, useContext, useState, useCallback, useEffect, ReactNode } from "react";

export type Language = "zh" | "zh-TW" | "en" | "ko" | "ja" | "th" | "vi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

type Dict = Record<string, string>;

const en: Dict = {
  "app.title": "B18 Token Economics",
  "app.subtitle": "DeFi Protocol Calculator",
  "button.reset": "Reset",
  "button.resetAll": "Reset All Data",
  "button.calculate": "Calculate",
  "button.confirm": "Confirm",
  "button.cancel": "Cancel",
  "button.add": "Add",
  "button.remove": "Remove",

  "metrics.price": "B18 Price",
  "metrics.circulation": "Circulation",
  "metrics.treasury": "Treasury",
  "metrics.burned": "Burned",
  "metrics.delivery": "Delivery Contract",
  "metrics.lpUsdt": "LP USDC",
  "metrics.lpB18": "LP B18",
  "metrics.fromDelivery": "from Delivery",
  "metrics.bonusPool": "Bonus Pool",

  "tab.staking": "Presale Staking",
  "tab.secondary": "Secondary Market",
  "tab.release": "Release & Withdrawal",
  "tab.rewards": "Dynamic Rewards",
  "tab.distribution": "Token Distribution",
  "tab.summary": "Summary",
  "tab.simulator": "Cash Flow Simulator",
  "tabs.staking": "Staking",
  "tabs.secondary": "Market",
  "tabs.release": "Release",
  "tabs.rewards": "Rewards",
  "tabs.distribution": "Distribution",
  "tabs.summary": "Summary",
  "tabs.simulator": "Cash Flow",

  "staking.title": "Presale Staking Calculator",
  "staking.desc": "Presale purchase with no slippage, USDC split: 50% to treasury, 50% to LP. Delivery contract adds matching B18 to LP to maintain price stability. Tokens are released daily after staking.",
  "staking.params": "Investment Parameters",
  "staking.amount": "Investment Amount (USDC, min 100)",
  "staking.period": "Staking Period",
  "staking.releasePeriod": "Release Period",
  "staking.compound": "Daily Compounding",
  "staking.compoundDesc": "Enable compounding: daily principal + interest = next day principal",
  "staking.flow": "Investment Flow",
  "staking.fundFlow": "Fund Flow (No Slippage)",
  "staking.toTreasury": "To Treasury",
  "staking.toLP": "To LP Pool",
  "staking.deliveryLP": "Delivery Contract Adds to LP",
  "staking.lpMatch": "Match 50% USDC, maintain price stability",
  "staking.priceImpact": "Price Impact",
  "staking.priceStable": "Price Stays Stable",
  "staking.priceStableDesc": "Delivery contract adds matching B18 to LP, USDC and B18 increase proportionally, price stays stable",
  "staking.returns": "Investment Returns",
  "staking.tokensReceived": "Tokens Received",
  "staking.stakingReturns": "Staking Returns",
  "staking.totalReturn": "Total Interest",
  "staking.releaseTax": "Release Tax",
  "staking.totalPeriod": "Total Period",
  "staking.days": "days",
  "staking.principal": "Principal",
  "staking.noSlippage": "Presale No Slippage",
  "staking.stakingPL": "Staking P&L",
  "staking.dailyProfit": "Daily Profit",
  "staking.netProfit": "Net Profit",
  "staking.simulate": "Simulate Purchase & Stake",
  "staking.details": "Detailed Breakdown",

  "secondary.title": "Secondary Market Trading",
  "secondary.desc": "AMM trading with 3% slippage fee, 60% to treasury, 20% burn, 20% to bonus pool",
  "secondary.buy": "Buy",
  "secondary.sell": "Sell",
  "secondary.buyAmount": "Buy Amount (USDC)",
  "secondary.sellAmount": "Sell Amount (B18)",
  "secondary.priceInfo": "Price Information",
  "secondary.currentPrice": "Current Price",
  "secondary.afterPrice": "Price After Trade",
  "secondary.slippage": "Slippage",
  "secondary.slippageFee": "Slippage Fee",
  "secondary.feeDistribution": "Fee Distribution",
  "secondary.toTreasury": "To Treasury",
  "secondary.toBurn": "Burn",
  "secondary.toBonus": "To Bonus Pool",
  "secondary.tradeResult": "Trade Result",
  "secondary.tokensReceived": "Tokens Received",
  "secondary.usdtReceived": "USDC Received",
  "secondary.simulateBuy": "Simulate Buy",
  "secondary.simulateSell": "Simulate Sell",

  "release.title": "Release & Withdrawal",
  "release.desc": "Release staked tokens for USDC. Treasury pays in USDC, released B18 distributed: 60% to delivery contract, 20% burn, 20% bonus pool.",
  "release.simulator": "Release Withdrawal Simulator",
  "release.stakedTokens": "Staked Tokens (from staking calculator)",
  "release.stakedAmount": "Staked Amount (P+I)",
  "release.releasePeriod": "Release Period",
  "release.releaseResult": "Release Result",
  "release.dailyRelease": "Daily Release",
  "release.monthlyRelease": "Monthly Release",
  "release.totalRelease": "Total Release",
  "release.releaseTax": "Release Tax",
  "release.netRelease": "Net Release",
  "release.withdrawalPayout": "Withdrawal Payout",
  "release.b18Distribution": "B18 Distribution After Payout",
  "release.toDelivery": "To Delivery Contract",
  "release.toBurn": "Burn (Black Hole)",
  "release.toBonus": "Bonus Pool",
  "release.simulateRelease": "Simulate Release",
  "release.params": "Release Parameters",
  "release.withdrawDays": "Withdraw Days",
  "release.simulationDay": "Simulation Day",
  "release.calculateDay": "Calculate Day",
  "release.dayStatus": "Day Status",
  "release.treasuryBalance": "Treasury Balance",
  "release.currentPrice": "Current Price",
  "release.preview": "Release Preview",
  "release.taxAmount": "Tax Amount",
  "release.taxRate": "Tax Rate",
  "release.taxB18": "Tax B18",
  "release.taxUsdt": "Tax USDC Value",
  "release.taxBuyback": "Tax Buyback Impact",
  "release.confirmRelease": "Confirm Release",
  "release.cashflow": "Cash Flow Status",
  "release.sufficient": "Sufficient",
  "release.insufficient": "Insufficient",
  "release.queueRequired": "Queue Required",
  "release.dayPayout": "Day Payout Required",

  "rewards.title": "Dynamic Rewards Calculator",
  "rewards.desc": "V1-V10 tier cumulative rewards based on team performance",
  "rewards.tierTab": "Tier Rewards",
  "rewards.layerTab": "Performance Rewards",
  "rewards.memberTier": "Member Tier",
  "rewards.qualifyingRange": "Qualifying Range",
  "rewards.teamPerformance": "Team Performance (10K USDC)",
  "rewards.currentTier": "Current Tier",
  "rewards.rewardRate": "Reward Rate",
  "rewards.grossReward": "Gross Reward",
  "rewards.releaseTax": "Release Tax",
  "rewards.netReward": "Net Reward",
  "rewards.rewardFormula": "Reward Formula",
  "rewards.performanceTokens": "Performance Tokens",
  "rewards.baseReward": "Base Reward",
  "rewards.tierReward": "Tier Reward",
  "rewards.taxPurchase": "Tax Purchase Required",
  "rewards.treasuryPays": "Treasury Pays",
  "rewards.taxDistribution": "Tax B18 Distribution",
  "rewards.dailyReward": "Daily Reward",
  "rewards.monthlyReward": "Monthly Reward",
  "rewards.annualReward": "Annual Reward",
  "rewards.layerNumber": "Layer",
  "rewards.layerPerformance": "Layer Performance",
  "rewards.layerPercent": "Layer Percent",
  "rewards.layerReward": "Layer Reward",
  "rewards.networkPerformance": "Network Performance",
  "rewards.totalLayers": "Total Layers",
  "rewards.addLayer": "Add Layer",
  "rewards.bonusPool": "Bonus Pool",
  "rewards.performanceRatio": "Performance Ratio",
  "rewards.totalPerformance": "Total Performance",
  "rewards.totalReward": "Total Reward",
  "rewards.warning": "Warning",
  "rewards.exceedsNetwork": "Total exceeds network performance",

  "distribution.title": "Token Distribution",
  "distribution.circulation": "Circulation",
  "distribution.delivery": "Delivery Contract",
  "distribution.burned": "Burned",
  "distribution.bonusPool": "Bonus Pool",
  "distribution.lpPool": "LP Pool",

  "summary.title": "Calculation Summary",
  "summary.stakingInput": "Staking Input",
  "summary.secondaryMarket": "Secondary Market",
  "summary.releaseWithdraw": "Release & Withdrawal",
  "summary.dynamicRewards": "Dynamic Rewards",
  "summary.totalInvestment": "Total Investment",
  "summary.netProfit": "Net Profit",
  "summary.totalReturns": "Total Returns",
  "summary.totalTax": "Total Tax",
  "summary.tierAndPerformance": "Tier + Performance",
  "summary.noData": "Complete calculations in tabs below to see summary",
  "summary.investment": "Investment",
  "summary.profit": "Profit",
  "summary.tax": "Tax",

  "simulator.title": "Cash Flow Simulator",
  "simulator.desc": "Day-by-day simulation of treasury cash flow with funding protection",

  "footer.chain": "Base Chain",
  "footer.totalSupply": "Total Supply",
  "footer.initialCirculation": "Initial Circulation",
  "footer.deliveryContract": "Delivery Contract",
  "footer.title": "B18 Token Economics Calculator",
  "footer.stats": "Base Chain | Total: 10.1M | Initial: 100K | Delivery: 10M",

  "common.day": "day",
  "common.days": "days",
  "common.month": "month",
  "common.year": "year",
  "common.daily": "Daily",
  "common.monthly": "Monthly",
  "common.annual": "Annual",
  "common.total": "Total",
  "common.net": "Net",
  "common.gross": "Gross",
  "common.rate": "Rate",
  "common.amount": "Amount",
  "common.tokens": "Tokens",
  "common.price": "Price",
  "common.value": "Value",
  "common.balance": "Balance",
  "common.status": "Status",
  "common.times30": "x30",
  "common.times360": "x360",
};

const zh: Dict = {
  "app.title": "B18 代币经济模型",
  "app.subtitle": "DeFi 协议计算器",
  "button.reset": "重置",
  "button.resetAll": "重置所有数据",
  "button.calculate": "计算",
  "button.confirm": "确认",
  "button.cancel": "取消",
  "button.add": "添加",
  "button.remove": "删除",

  "metrics.price": "B18 价格",
  "metrics.circulation": "流通量",
  "metrics.treasury": "国库余额",
  "metrics.burned": "已销毁",
  "metrics.delivery": "交付合约",
  "metrics.lpUsdt": "LP USDC",
  "metrics.lpB18": "LP B18",
  "metrics.fromDelivery": "来自交付合约",
  "metrics.bonusPool": "奖励池",

  "tab.staking": "一级市场质押",
  "tab.secondary": "二级市场交易",
  "tab.release": "释放提现",
  "tab.rewards": "动态奖励",
  "tab.distribution": "代币分布",
  "tab.summary": "统计汇总",
  "tab.simulator": "现金流模拟",
  "tabs.staking": "质押计算",
  "tabs.secondary": "二级市场",
  "tabs.release": "释放提现",
  "tabs.rewards": "动态奖励",
  "tabs.distribution": "代币分配",
  "tabs.summary": "统计汇总",
  "tabs.simulator": "现金流模拟",

  "staking.title": "一级市场质押计算",
  "staking.desc": "预售购买无滑点，USDC分配：50%进国库，50%进LP。交付合约同时添加等值B18到LP维持价格稳定。代币质押后按日释放。",
  "staking.params": "投资参数",
  "staking.amount": "投入金额 (USDC，最低100)",
  "staking.period": "质押周期",
  "staking.releasePeriod": "释放周期",
  "staking.compound": "每日本利复投",
  "staking.compoundDesc": "开启复利：每日本金+利息=第二天本金，按日利率滚存",
  "staking.flow": "投资流程",
  "staking.fundFlow": "资金流向（无滑点）",
  "staking.toTreasury": "进国库",
  "staking.toLP": "进LP底池",
  "staking.deliveryLP": "交付合约添加LP流动性",
  "staking.lpMatch": "配比50% USDC，维持价格稳定",
  "staking.priceImpact": "价格影响",
  "staking.priceStable": "价格保持稳定",
  "staking.priceStableDesc": "交付合约同时添加等值B18到LP，USDC与B18同比例增加，价格保持稳定",
  "staking.returns": "投资收益",
  "staking.tokensReceived": "获得代币",
  "staking.stakingReturns": "质押收益",
  "staking.totalReturn": "总共利息",
  "staking.releaseTax": "释放税",
  "staking.totalPeriod": "总周期",
  "staking.days": "天",
  "staking.principal": "投入本金",
  "staking.noSlippage": "预售无滑点",
  "staking.stakingPL": "质押本利",
  "staking.dailyProfit": "日均收益",
  "staking.netProfit": "净收益",
  "staking.simulate": "模拟购买质押",
  "staking.details": "收益明细",

  "secondary.title": "二级市场交易",
  "secondary.desc": "AMM交易，3%滑点费用，60%进国库，20%销毁，20%进奖金池",
  "secondary.buy": "买入",
  "secondary.sell": "卖出",
  "secondary.buyAmount": "买入金额 (USDC)",
  "secondary.sellAmount": "卖出数量 (B18)",
  "secondary.priceInfo": "价格信息",
  "secondary.currentPrice": "当前价格",
  "secondary.afterPrice": "交易后价格",
  "secondary.slippage": "滑点",
  "secondary.slippageFee": "滑点费用",
  "secondary.feeDistribution": "费用分配",
  "secondary.toTreasury": "进国库",
  "secondary.toBurn": "销毁",
  "secondary.toBonus": "进奖金池",
  "secondary.tradeResult": "交易结果",
  "secondary.tokensReceived": "获得代币",
  "secondary.usdtReceived": "获得USDC",
  "secondary.simulateBuy": "模拟买入",
  "secondary.simulateSell": "模拟卖出",

  "release.title": "释放提现",
  "release.desc": "释放质押代币换取USDC。国库用USDC兑付，释放的B18分配：60%回交付合约、20%销毁、20%奖金池。",
  "release.simulator": "释放提现模拟",
  "release.stakedTokens": "质押代币（来自质押计算）",
  "release.stakedAmount": "质押量 (本+利)",
  "release.releasePeriod": "释放周期",
  "release.releaseResult": "释放结果",
  "release.dailyRelease": "每日释放",
  "release.monthlyRelease": "月释放",
  "release.totalRelease": "总释放量",
  "release.releaseTax": "释放税",
  "release.netRelease": "净释放",
  "release.withdrawalPayout": "提现兑付",
  "release.b18Distribution": "提现被兑付后的B18分配",
  "release.toDelivery": "回交付合约",
  "release.toBurn": "黑洞销毁",
  "release.toBonus": "奖金池",
  "release.simulateRelease": "模拟释放",
  "release.params": "释放参数",
  "release.withdrawDays": "提现天数",
  "release.simulationDay": "模拟天数",
  "release.calculateDay": "计算第X天",
  "release.dayStatus": "当天状态",
  "release.treasuryBalance": "国库余额",
  "release.currentPrice": "当前价格",
  "release.preview": "释放预览",
  "release.taxAmount": "税费金额",
  "release.taxRate": "税率",
  "release.taxB18": "税费B18",
  "release.taxUsdt": "税费USDC价值",
  "release.taxBuyback": "税费回购影响",
  "release.confirmRelease": "确认释放",
  "release.cashflow": "现金流状态",
  "release.sufficient": "充足",
  "release.insufficient": "不足",
  "release.queueRequired": "需要排队",
  "release.dayPayout": "当天需要支付",

  "rewards.title": "动态奖励计算器",
  "rewards.desc": "V1-V10等级累进奖励，基于团队业绩",
  "rewards.tierTab": "级别奖励",
  "rewards.layerTab": "业绩奖励",
  "rewards.memberTier": "会员等级",
  "rewards.qualifyingRange": "达标区间",
  "rewards.teamPerformance": "小区业绩（万U）",
  "rewards.currentTier": "当前等级",
  "rewards.rewardRate": "奖励比例",
  "rewards.grossReward": "毛奖励",
  "rewards.releaseTax": "释放税",
  "rewards.netReward": "净奖励",
  "rewards.rewardFormula": "奖励公式",
  "rewards.performanceTokens": "业绩代币",
  "rewards.baseReward": "基础奖励",
  "rewards.tierReward": "级别奖励",
  "rewards.taxPurchase": "需购买税费",
  "rewards.treasuryPays": "国库支付",
  "rewards.taxDistribution": "税费B18分配",
  "rewards.dailyReward": "日奖励",
  "rewards.monthlyReward": "月奖励",
  "rewards.annualReward": "年奖励",
  "rewards.layerNumber": "层",
  "rewards.layerPerformance": "层业绩",
  "rewards.layerPercent": "层比例",
  "rewards.layerReward": "层奖励",
  "rewards.networkPerformance": "全网业绩",
  "rewards.totalLayers": "总层数",
  "rewards.addLayer": "添加层",
  "rewards.bonusPool": "奖金池",
  "rewards.performanceRatio": "业绩占比",
  "rewards.totalPerformance": "总业绩",
  "rewards.totalReward": "总奖励",
  "rewards.warning": "警告",
  "rewards.exceedsNetwork": "总业绩超过全网业绩",

  "distribution.title": "代币分布",
  "distribution.circulation": "流通量",
  "distribution.delivery": "交付合约",
  "distribution.burned": "已销毁",
  "distribution.bonusPool": "奖金池",
  "distribution.lpPool": "LP池",

  "summary.title": "总计算统计",
  "summary.stakingInput": "质押投入",
  "summary.secondaryMarket": "二级市场",
  "summary.releaseWithdraw": "释放提现",
  "summary.dynamicRewards": "动态奖励",
  "summary.totalInvestment": "总投入",
  "summary.netProfit": "净利润",
  "summary.totalReturns": "总收益",
  "summary.totalTax": "总税费",
  "summary.tierAndPerformance": "级别+业绩",
  "summary.noData": "在下方各标签页进行计算后，这里将显示汇总结果",
  "summary.investment": "投入",
  "summary.profit": "利润",
  "summary.tax": "税费",

  "simulator.title": "现金流模拟",
  "simulator.desc": "逐日模拟国库现金流，包含资金保护机制",

  "footer.chain": "Base链",
  "footer.totalSupply": "总发行量",
  "footer.initialCirculation": "初始流通",
  "footer.deliveryContract": "交付合约",
  "footer.title": "B18 代币经济模型计算器",
  "footer.stats": "Base链 | 总发行量: 1,010万 | 初始流通: 10万 | 交付合约: 1,000万",

  "common.day": "天",
  "common.days": "天",
  "common.month": "月",
  "common.year": "年",
  "common.daily": "日",
  "common.monthly": "月",
  "common.annual": "年",
  "common.total": "总计",
  "common.net": "净",
  "common.gross": "毛",
  "common.rate": "率",
  "common.amount": "金额",
  "common.tokens": "代币",
  "common.price": "价格",
  "common.value": "价值",
  "common.balance": "余额",
  "common.status": "状态",
  "common.times30": "x30",
  "common.times360": "x360",
};

const zhTW: Dict = {
  "app.title": "B18 代幣經濟模型",
  "app.subtitle": "DeFi 協議計算器",
  "button.reset": "重置",
  "button.resetAll": "重置所有資料",
  "button.calculate": "計算",
  "button.confirm": "確認",
  "button.cancel": "取消",
  "button.add": "新增",
  "button.remove": "移除",

  "metrics.price": "B18 價格",
  "metrics.circulation": "流通量",
  "metrics.treasury": "國庫餘額",
  "metrics.burned": "已銷毀",
  "metrics.delivery": "交付合約",
  "metrics.lpUsdt": "LP USDC",
  "metrics.lpB18": "LP B18",
  "metrics.fromDelivery": "來自交付合約",
  "metrics.bonusPool": "獎勵池",

  "tab.staking": "一級市場質押",
  "tab.secondary": "二級市場交易",
  "tab.release": "釋放提現",
  "tab.rewards": "動態獎勵",
  "tab.distribution": "代幣分佈",
  "tab.summary": "統計匯總",
  "tab.simulator": "現金流模擬",
  "tabs.staking": "質押計算",
  "tabs.secondary": "二級市場",
  "tabs.release": "釋放提現",
  "tabs.rewards": "動態獎勵",
  "tabs.distribution": "代幣分配",
  "tabs.summary": "統計匯總",
  "tabs.simulator": "現金流模擬",

  "staking.title": "一級市場質押計算",
  "staking.desc": "預售購買無滑點，USDC 分配：50% 進國庫，50% 進 LP。交付合約同時新增等值 B18 到 LP，維持價格穩定。代幣質押後按日釋放。",
  "staking.params": "投資參數",
  "staking.amount": "投入金額 (USDC，最低 100)",
  "staking.period": "質押週期",
  "staking.releasePeriod": "釋放週期",
  "staking.compound": "每日本利複投",
  "staking.compoundDesc": "開啟複利：每日本金+利息=隔日本金，按日利率滾存",
  "staking.flow": "投資流程",
  "staking.fundFlow": "資金流向（無滑點）",
  "staking.toTreasury": "進國庫",
  "staking.toLP": "進 LP 底池",
  "staking.deliveryLP": "交付合約新增 LP 流動性",
  "staking.lpMatch": "配比 50% USDC，維持價格穩定",
  "staking.priceImpact": "價格影響",
  "staking.priceStable": "價格保持穩定",
  "staking.priceStableDesc": "交付合約同時新增等值 B18 到 LP，USDC 與 B18 同比例增加，價格保持穩定",
  "staking.returns": "投資收益",
  "staking.tokensReceived": "取得代幣",
  "staking.stakingReturns": "質押收益",
  "staking.totalReturn": "總共利息",
  "staking.releaseTax": "釋放稅",
  "staking.totalPeriod": "總週期",
  "staking.days": "天",
  "staking.principal": "投入本金",
  "staking.noSlippage": "預售無滑點",
  "staking.stakingPL": "質押本利",
  "staking.dailyProfit": "日均收益",
  "staking.netProfit": "淨收益",
  "staking.simulate": "模擬購買質押",
  "staking.details": "收益明細",

  "secondary.title": "二級市場交易",
  "secondary.desc": "AMM 交易，3% 滑點費用，60% 進國庫，20% 銷毀，20% 進獎金池",
  "secondary.buy": "買入",
  "secondary.sell": "賣出",
  "secondary.buyAmount": "買入金額 (USDC)",
  "secondary.sellAmount": "賣出數量 (B18)",
  "secondary.priceInfo": "價格資訊",
  "secondary.currentPrice": "目前價格",
  "secondary.afterPrice": "交易後價格",
  "secondary.slippage": "滑點",
  "secondary.slippageFee": "滑點費用",
  "secondary.feeDistribution": "費用分配",
  "secondary.toTreasury": "進國庫",
  "secondary.toBurn": "銷毀",
  "secondary.toBonus": "進獎金池",
  "secondary.tradeResult": "交易結果",
  "secondary.tokensReceived": "取得代幣",
  "secondary.usdtReceived": "取得 USDC",
  "secondary.simulateBuy": "模擬買入",
  "secondary.simulateSell": "模擬賣出",

  "release.title": "釋放提現",
  "release.desc": "釋放質押代幣換取 USDC。國庫以 USDC 兌付，釋放的 B18 分配：60% 回交付合約、20% 銷毀、20% 獎金池。",
  "release.simulator": "釋放提現模擬",
  "release.stakedTokens": "質押代幣（來自質押計算）",
  "release.stakedAmount": "質押量 (本+利)",
  "release.releasePeriod": "釋放週期",
  "release.releaseResult": "釋放結果",
  "release.dailyRelease": "每日釋放",
  "release.monthlyRelease": "月釋放",
  "release.totalRelease": "總釋放量",
  "release.releaseTax": "釋放稅",
  "release.netRelease": "淨釋放",
  "release.withdrawalPayout": "提現兌付",
  "release.b18Distribution": "提現被兌付後的 B18 分配",
  "release.toDelivery": "回交付合約",
  "release.toBurn": "黑洞銷毀",
  "release.toBonus": "獎金池",
  "release.simulateRelease": "模擬釋放",
  "release.params": "釋放參數",
  "release.withdrawDays": "提現天數",
  "release.simulationDay": "模擬天數",
  "release.calculateDay": "計算第 X 天",
  "release.dayStatus": "當天狀態",
  "release.treasuryBalance": "國庫餘額",
  "release.currentPrice": "目前價格",
  "release.preview": "釋放預覽",
  "release.taxAmount": "稅費金額",
  "release.taxRate": "稅率",
  "release.taxB18": "稅費 B18",
  "release.taxUsdt": "稅費 USDC 價值",
  "release.taxBuyback": "稅費回購影響",
  "release.confirmRelease": "確認釋放",
  "release.cashflow": "現金流狀態",
  "release.sufficient": "充足",
  "release.insufficient": "不足",
  "release.queueRequired": "需要排隊",
  "release.dayPayout": "當天需要支付",

  "rewards.title": "動態獎勵計算器",
  "rewards.desc": "V1-V10 等級累進獎勵，基於團隊業績",
  "rewards.tierTab": "級別獎勵",
  "rewards.layerTab": "業績獎勵",
  "rewards.memberTier": "會員等級",
  "rewards.qualifyingRange": "達標區間",
  "rewards.teamPerformance": "小區業績（萬 U）",
  "rewards.currentTier": "目前等級",
  "rewards.rewardRate": "獎勵比例",
  "rewards.grossReward": "毛獎勵",
  "rewards.releaseTax": "釋放稅",
  "rewards.netReward": "淨獎勵",
  "rewards.rewardFormula": "獎勵公式",
  "rewards.performanceTokens": "業績代幣",
  "rewards.baseReward": "基礎獎勵",
  "rewards.tierReward": "級別獎勵",
  "rewards.taxPurchase": "需購買稅費",
  "rewards.treasuryPays": "國庫支付",
  "rewards.taxDistribution": "稅費 B18 分配",
  "rewards.dailyReward": "日獎勵",
  "rewards.monthlyReward": "月獎勵",
  "rewards.annualReward": "年獎勵",
  "rewards.layerNumber": "層",
  "rewards.layerPerformance": "層業績",
  "rewards.layerPercent": "層比例",
  "rewards.layerReward": "層獎勵",
  "rewards.networkPerformance": "全網業績",
  "rewards.totalLayers": "總層數",
  "rewards.addLayer": "新增層",
  "rewards.bonusPool": "獎金池",
  "rewards.performanceRatio": "業績佔比",
  "rewards.totalPerformance": "總業績",
  "rewards.totalReward": "總獎勵",
  "rewards.warning": "警告",
  "rewards.exceedsNetwork": "總業績超過全網業績",

  "distribution.title": "代幣分佈",
  "distribution.circulation": "流通量",
  "distribution.delivery": "交付合約",
  "distribution.burned": "已銷毀",
  "distribution.bonusPool": "獎金池",
  "distribution.lpPool": "LP 池",

  "summary.title": "總計算統計",
  "summary.stakingInput": "質押投入",
  "summary.secondaryMarket": "二級市場",
  "summary.releaseWithdraw": "釋放提現",
  "summary.dynamicRewards": "動態獎勵",
  "summary.totalInvestment": "總投入",
  "summary.netProfit": "淨利潤",
  "summary.totalReturns": "總收益",
  "summary.totalTax": "總稅費",
  "summary.tierAndPerformance": "級別+業績",
  "summary.noData": "於下方各分頁進行計算後，此處將顯示匯總結果",
  "summary.investment": "投入",
  "summary.profit": "利潤",
  "summary.tax": "稅費",

  "simulator.title": "現金流模擬",
  "simulator.desc": "逐日模擬國庫現金流，包含資金保護機制",

  "footer.chain": "Base 鏈",
  "footer.totalSupply": "總發行量",
  "footer.initialCirculation": "初始流通",
  "footer.deliveryContract": "交付合約",
  "footer.title": "B18 代幣經濟模型計算器",
  "footer.stats": "Base 鏈 | 總發行量: 1,010 萬 | 初始流通: 10 萬 | 交付合約: 1,000 萬",

  "common.day": "天",
  "common.days": "天",
  "common.month": "月",
  "common.year": "年",
  "common.daily": "日",
  "common.monthly": "月",
  "common.annual": "年",
  "common.total": "總計",
  "common.net": "淨",
  "common.gross": "毛",
  "common.rate": "率",
  "common.amount": "金額",
  "common.tokens": "代幣",
  "common.price": "價格",
  "common.value": "價值",
  "common.balance": "餘額",
  "common.status": "狀態",
  "common.times30": "x30",
  "common.times360": "x360",
};

const ko: Dict = {
  "app.title": "B18 토큰 이코노믹스",
  "app.subtitle": "DeFi 프로토콜 계산기",
  "button.reset": "초기화",
  "button.resetAll": "모든 데이터 초기화",
  "button.calculate": "계산",
  "button.confirm": "확인",
  "button.cancel": "취소",
  "button.add": "추가",
  "button.remove": "삭제",

  "metrics.price": "B18 가격",
  "metrics.circulation": "유통량",
  "metrics.treasury": "트레저리",
  "metrics.burned": "소각됨",
  "metrics.delivery": "배포 계약",
  "metrics.lpUsdt": "LP USDC",
  "metrics.lpB18": "LP B18",
  "metrics.fromDelivery": "배포 계약에서",
  "metrics.bonusPool": "보너스 풀",

  "tab.staking": "프리세일 스테이킹",
  "tab.secondary": "2차 시장",
  "tab.release": "해제 및 출금",
  "tab.rewards": "동적 보상",
  "tab.distribution": "토큰 분포",
  "tab.summary": "요약",
  "tab.simulator": "현금 흐름 시뮬레이터",
  "tabs.staking": "스테이킹",
  "tabs.secondary": "시장",
  "tabs.release": "해제",
  "tabs.rewards": "보상",
  "tabs.distribution": "분포",
  "tabs.summary": "요약",
  "tabs.simulator": "현금 흐름",

  "staking.title": "프리세일 스테이킹 계산기",
  "staking.desc": "프리세일 구매는 슬리피지가 없으며 USDC가 분할됩니다: 50%는 트레저리로, 50%는 LP로. 배포 계약이 동일한 B18을 LP에 추가하여 가격 안정성을 유지합니다. 토큰은 스테이킹 후 매일 해제됩니다.",
  "staking.params": "투자 파라미터",
  "staking.amount": "투자 금액 (USDC, 최소 100)",
  "staking.period": "스테이킹 기간",
  "staking.releasePeriod": "해제 기간",
  "staking.compound": "일일 복리",
  "staking.compoundDesc": "복리 활성화: 일일 원금 + 이자 = 다음 날 원금",
  "staking.flow": "투자 흐름",
  "staking.fundFlow": "자금 흐름 (슬리피지 없음)",
  "staking.toTreasury": "트레저리로",
  "staking.toLP": "LP 풀로",
  "staking.deliveryLP": "배포 계약이 LP에 추가",
  "staking.lpMatch": "50% USDC 매칭, 가격 안정성 유지",
  "staking.priceImpact": "가격 영향",
  "staking.priceStable": "가격 안정 유지",
  "staking.priceStableDesc": "배포 계약이 동일한 B18을 LP에 추가하여 USDC와 B18이 비례하여 증가하므로 가격이 안정됩니다",
  "staking.returns": "투자 수익",
  "staking.tokensReceived": "받은 토큰",
  "staking.stakingReturns": "스테이킹 수익",
  "staking.totalReturn": "총 이자",
  "staking.releaseTax": "해제 세금",
  "staking.totalPeriod": "총 기간",
  "staking.days": "일",
  "staking.principal": "원금",
  "staking.noSlippage": "프리세일 슬리피지 없음",
  "staking.stakingPL": "스테이킹 손익",
  "staking.dailyProfit": "일일 수익",
  "staking.netProfit": "순수익",
  "staking.simulate": "구매 및 스테이킹 시뮬레이션",
  "staking.details": "상세 내역",

  "secondary.title": "2차 시장 거래",
  "secondary.desc": "3% 슬리피지 수수료를 가진 AMM 거래, 60% 트레저리, 20% 소각, 20% 보너스 풀",
  "secondary.buy": "매수",
  "secondary.sell": "매도",
  "secondary.buyAmount": "매수 금액 (USDC)",
  "secondary.sellAmount": "매도 수량 (B18)",
  "secondary.priceInfo": "가격 정보",
  "secondary.currentPrice": "현재 가격",
  "secondary.afterPrice": "거래 후 가격",
  "secondary.slippage": "슬리피지",
  "secondary.slippageFee": "슬리피지 수수료",
  "secondary.feeDistribution": "수수료 분배",
  "secondary.toTreasury": "트레저리로",
  "secondary.toBurn": "소각",
  "secondary.toBonus": "보너스 풀로",
  "secondary.tradeResult": "거래 결과",
  "secondary.tokensReceived": "받은 토큰",
  "secondary.usdtReceived": "받은 USDC",
  "secondary.simulateBuy": "매수 시뮬레이션",
  "secondary.simulateSell": "매도 시뮬레이션",

  "release.title": "해제 및 출금",
  "release.desc": "스테이킹된 토큰을 USDC로 해제합니다. 트레저리가 USDC로 지급하고 해제된 B18이 분배됩니다: 60% 배포 계약, 20% 소각, 20% 보너스 풀.",
  "release.simulator": "해제 출금 시뮬레이터",
  "release.stakedTokens": "스테이킹된 토큰 (스테이킹 계산기에서)",
  "release.stakedAmount": "스테이킹 금액 (원금+이자)",
  "release.releasePeriod": "해제 기간",
  "release.releaseResult": "해제 결과",
  "release.dailyRelease": "일일 해제",
  "release.monthlyRelease": "월간 해제",
  "release.totalRelease": "총 해제",
  "release.releaseTax": "해제 세금",
  "release.netRelease": "순 해제",
  "release.withdrawalPayout": "출금 지급",
  "release.b18Distribution": "지급 후 B18 분배",
  "release.toDelivery": "배포 계약으로",
  "release.toBurn": "소각 (블랙홀)",
  "release.toBonus": "보너스 풀",
  "release.simulateRelease": "해제 시뮬레이션",
  "release.params": "해제 파라미터",
  "release.withdrawDays": "출금 일수",
  "release.simulationDay": "시뮬레이션 일",
  "release.calculateDay": "일 계산",
  "release.dayStatus": "당일 상태",
  "release.treasuryBalance": "트레저리 잔액",
  "release.currentPrice": "현재 가격",
  "release.preview": "해제 미리보기",
  "release.taxAmount": "세금 금액",
  "release.taxRate": "세율",
  "release.taxB18": "세금 B18",
  "release.taxUsdt": "세금 USDC 가치",
  "release.taxBuyback": "세금 바이백 영향",
  "release.confirmRelease": "해제 확인",
  "release.cashflow": "현금 흐름 상태",
  "release.sufficient": "충분함",
  "release.insufficient": "부족함",
  "release.queueRequired": "대기 필요",
  "release.dayPayout": "당일 지급 필요",

  "rewards.title": "동적 보상 계산기",
  "rewards.desc": "팀 성과에 기반한 V1-V10 등급 누적 보상",
  "rewards.tierTab": "등급 보상",
  "rewards.layerTab": "성과 보상",
  "rewards.memberTier": "회원 등급",
  "rewards.qualifyingRange": "자격 범위",
  "rewards.teamPerformance": "팀 성과 (10K USDC)",
  "rewards.currentTier": "현재 등급",
  "rewards.rewardRate": "보상 비율",
  "rewards.grossReward": "총 보상",
  "rewards.releaseTax": "해제 세금",
  "rewards.netReward": "순 보상",
  "rewards.rewardFormula": "보상 공식",
  "rewards.performanceTokens": "성과 토큰",
  "rewards.baseReward": "기본 보상",
  "rewards.tierReward": "등급 보상",
  "rewards.taxPurchase": "세금 구매 필요",
  "rewards.treasuryPays": "트레저리 지급",
  "rewards.taxDistribution": "세금 B18 분배",
  "rewards.dailyReward": "일일 보상",
  "rewards.monthlyReward": "월간 보상",
  "rewards.annualReward": "연간 보상",
  "rewards.layerNumber": "레이어",
  "rewards.layerPerformance": "레이어 성과",
  "rewards.layerPercent": "레이어 비율",
  "rewards.layerReward": "레이어 보상",
  "rewards.networkPerformance": "네트워크 성과",
  "rewards.totalLayers": "총 레이어",
  "rewards.addLayer": "레이어 추가",
  "rewards.bonusPool": "보너스 풀",
  "rewards.performanceRatio": "성과 비율",
  "rewards.totalPerformance": "총 성과",
  "rewards.totalReward": "총 보상",
  "rewards.warning": "경고",
  "rewards.exceedsNetwork": "총합이 네트워크 성과를 초과함",

  "distribution.title": "토큰 분포",
  "distribution.circulation": "유통량",
  "distribution.delivery": "배포 계약",
  "distribution.burned": "소각됨",
  "distribution.bonusPool": "보너스 풀",
  "distribution.lpPool": "LP 풀",

  "summary.title": "계산 요약",
  "summary.stakingInput": "스테이킹 입력",
  "summary.secondaryMarket": "2차 시장",
  "summary.releaseWithdraw": "해제 및 출금",
  "summary.dynamicRewards": "동적 보상",
  "summary.totalInvestment": "총 투자",
  "summary.netProfit": "순수익",
  "summary.totalReturns": "총 수익",
  "summary.totalTax": "총 세금",
  "summary.tierAndPerformance": "등급 + 성과",
  "summary.noData": "아래 탭에서 계산을 완료하면 요약이 표시됩니다",
  "summary.investment": "투자",
  "summary.profit": "수익",
  "summary.tax": "세금",

  "simulator.title": "현금 흐름 시뮬레이터",
  "simulator.desc": "자금 보호가 포함된 트레저리 현금 흐름의 일별 시뮬레이션",

  "footer.chain": "Base 체인",
  "footer.totalSupply": "총 공급량",
  "footer.initialCirculation": "초기 유통량",
  "footer.deliveryContract": "배포 계약",
  "footer.title": "B18 토큰 이코노믹스 계산기",
  "footer.stats": "Base 체인 | 총: 10.1M | 초기: 100K | 배포: 10M",

  "common.day": "일",
  "common.days": "일",
  "common.month": "월",
  "common.year": "년",
  "common.daily": "일간",
  "common.monthly": "월간",
  "common.annual": "연간",
  "common.total": "합계",
  "common.net": "순",
  "common.gross": "총",
  "common.rate": "비율",
  "common.amount": "금액",
  "common.tokens": "토큰",
  "common.price": "가격",
  "common.value": "가치",
  "common.balance": "잔액",
  "common.status": "상태",
  "common.times30": "x30",
  "common.times360": "x360",
};

const ja: Dict = {
  "app.title": "B18 トークンエコノミクス",
  "app.subtitle": "DeFi プロトコル計算機",
  "button.reset": "リセット",
  "button.resetAll": "すべてのデータをリセット",
  "button.calculate": "計算",
  "button.confirm": "確認",
  "button.cancel": "キャンセル",
  "button.add": "追加",
  "button.remove": "削除",

  "metrics.price": "B18 価格",
  "metrics.circulation": "流通量",
  "metrics.treasury": "トレジャリー",
  "metrics.burned": "バーン済み",
  "metrics.delivery": "デリバリーコントラクト",
  "metrics.lpUsdt": "LP USDC",
  "metrics.lpB18": "LP B18",
  "metrics.fromDelivery": "デリバリーから",
  "metrics.bonusPool": "ボーナスプール",

  "tab.staking": "プレセールステーキング",
  "tab.secondary": "セカンダリーマーケット",
  "tab.release": "リリースと引き出し",
  "tab.rewards": "動的報酬",
  "tab.distribution": "トークン分布",
  "tab.summary": "サマリー",
  "tab.simulator": "キャッシュフローシミュレーター",
  "tabs.staking": "ステーキング",
  "tabs.secondary": "マーケット",
  "tabs.release": "リリース",
  "tabs.rewards": "報酬",
  "tabs.distribution": "分布",
  "tabs.summary": "サマリー",
  "tabs.simulator": "キャッシュフロー",

  "staking.title": "プレセールステーキング計算機",
  "staking.desc": "プレセール購入はスリッページなし。USDC分配: 50%をトレジャリー、50%をLPへ。デリバリーコントラクトは同等のB18をLPに追加して価格安定性を維持します。ステーキング後、トークンは日次でリリースされます。",
  "staking.params": "投資パラメータ",
  "staking.amount": "投資額 (USDC、最低100)",
  "staking.period": "ステーキング期間",
  "staking.releasePeriod": "リリース期間",
  "staking.compound": "日次複利",
  "staking.compoundDesc": "複利を有効化: 日次元本+利息=翌日の元本",
  "staking.flow": "投資フロー",
  "staking.fundFlow": "資金フロー (スリッページなし)",
  "staking.toTreasury": "トレジャリーへ",
  "staking.toLP": "LPプールへ",
  "staking.deliveryLP": "デリバリーコントラクトがLPに追加",
  "staking.lpMatch": "50% USDCマッチング、価格安定性を維持",
  "staking.priceImpact": "価格への影響",
  "staking.priceStable": "価格は安定",
  "staking.priceStableDesc": "デリバリーコントラクトが同等のB18をLPに追加し、USDCとB18が比例して増加するため価格は安定します",
  "staking.returns": "投資収益",
  "staking.tokensReceived": "受け取ったトークン",
  "staking.stakingReturns": "ステーキング収益",
  "staking.totalReturn": "総利息",
  "staking.releaseTax": "リリース税",
  "staking.totalPeriod": "総期間",
  "staking.days": "日",
  "staking.principal": "元本",
  "staking.noSlippage": "プレセールスリッページなし",
  "staking.stakingPL": "ステーキング損益",
  "staking.dailyProfit": "日次利益",
  "staking.netProfit": "純利益",
  "staking.simulate": "購入とステーキングをシミュレート",
  "staking.details": "詳細内訳",

  "secondary.title": "セカンダリーマーケット取引",
  "secondary.desc": "3%のスリッページ手数料付きAMM取引、60%トレジャリー、20%バーン、20%ボーナスプール",
  "secondary.buy": "購入",
  "secondary.sell": "売却",
  "secondary.buyAmount": "購入額 (USDC)",
  "secondary.sellAmount": "売却数量 (B18)",
  "secondary.priceInfo": "価格情報",
  "secondary.currentPrice": "現在価格",
  "secondary.afterPrice": "取引後価格",
  "secondary.slippage": "スリッページ",
  "secondary.slippageFee": "スリッページ手数料",
  "secondary.feeDistribution": "手数料分配",
  "secondary.toTreasury": "トレジャリーへ",
  "secondary.toBurn": "バーン",
  "secondary.toBonus": "ボーナスプールへ",
  "secondary.tradeResult": "取引結果",
  "secondary.tokensReceived": "受け取ったトークン",
  "secondary.usdtReceived": "受け取ったUSDC",
  "secondary.simulateBuy": "購入をシミュレート",
  "secondary.simulateSell": "売却をシミュレート",

  "release.title": "リリースと引き出し",
  "release.desc": "ステーキングされたトークンをUSDCでリリース。トレジャリーがUSDCで支払い、リリースされたB18は分配: 60%デリバリーコントラクト、20%バーン、20%ボーナスプール。",
  "release.simulator": "リリース引き出しシミュレーター",
  "release.stakedTokens": "ステーキングされたトークン (ステーキング計算機から)",
  "release.stakedAmount": "ステーキング額 (元本+利息)",
  "release.releasePeriod": "リリース期間",
  "release.releaseResult": "リリース結果",
  "release.dailyRelease": "日次リリース",
  "release.monthlyRelease": "月次リリース",
  "release.totalRelease": "総リリース",
  "release.releaseTax": "リリース税",
  "release.netRelease": "純リリース",
  "release.withdrawalPayout": "引き出し支払い",
  "release.b18Distribution": "支払い後のB18分配",
  "release.toDelivery": "デリバリーコントラクトへ",
  "release.toBurn": "バーン (ブラックホール)",
  "release.toBonus": "ボーナスプール",
  "release.simulateRelease": "リリースをシミュレート",
  "release.params": "リリースパラメータ",
  "release.withdrawDays": "引き出し日数",
  "release.simulationDay": "シミュレーション日",
  "release.calculateDay": "日を計算",
  "release.dayStatus": "当日ステータス",
  "release.treasuryBalance": "トレジャリー残高",
  "release.currentPrice": "現在価格",
  "release.preview": "リリースプレビュー",
  "release.taxAmount": "税金額",
  "release.taxRate": "税率",
  "release.taxB18": "税金B18",
  "release.taxUsdt": "税金USDC価値",
  "release.taxBuyback": "税金バイバックの影響",
  "release.confirmRelease": "リリース確認",
  "release.cashflow": "キャッシュフロー状態",
  "release.sufficient": "十分",
  "release.insufficient": "不十分",
  "release.queueRequired": "キューが必要",
  "release.dayPayout": "当日支払い必要",

  "rewards.title": "動的報酬計算機",
  "rewards.desc": "チームパフォーマンスに基づくV1-V10ティア累積報酬",
  "rewards.tierTab": "ティア報酬",
  "rewards.layerTab": "パフォーマンス報酬",
  "rewards.memberTier": "メンバーティア",
  "rewards.qualifyingRange": "適格範囲",
  "rewards.teamPerformance": "チームパフォーマンス (10K USDC)",
  "rewards.currentTier": "現在のティア",
  "rewards.rewardRate": "報酬率",
  "rewards.grossReward": "総報酬",
  "rewards.releaseTax": "リリース税",
  "rewards.netReward": "純報酬",
  "rewards.rewardFormula": "報酬式",
  "rewards.performanceTokens": "パフォーマンストークン",
  "rewards.baseReward": "基本報酬",
  "rewards.tierReward": "ティア報酬",
  "rewards.taxPurchase": "税金購入必要",
  "rewards.treasuryPays": "トレジャリー支払い",
  "rewards.taxDistribution": "税金B18分配",
  "rewards.dailyReward": "日次報酬",
  "rewards.monthlyReward": "月次報酬",
  "rewards.annualReward": "年次報酬",
  "rewards.layerNumber": "レイヤー",
  "rewards.layerPerformance": "レイヤーパフォーマンス",
  "rewards.layerPercent": "レイヤー比率",
  "rewards.layerReward": "レイヤー報酬",
  "rewards.networkPerformance": "ネットワークパフォーマンス",
  "rewards.totalLayers": "総レイヤー",
  "rewards.addLayer": "レイヤー追加",
  "rewards.bonusPool": "ボーナスプール",
  "rewards.performanceRatio": "パフォーマンス比率",
  "rewards.totalPerformance": "総パフォーマンス",
  "rewards.totalReward": "総報酬",
  "rewards.warning": "警告",
  "rewards.exceedsNetwork": "合計がネットワークパフォーマンスを超過",

  "distribution.title": "トークン分布",
  "distribution.circulation": "流通量",
  "distribution.delivery": "デリバリーコントラクト",
  "distribution.burned": "バーン済み",
  "distribution.bonusPool": "ボーナスプール",
  "distribution.lpPool": "LPプール",

  "summary.title": "計算サマリー",
  "summary.stakingInput": "ステーキング入力",
  "summary.secondaryMarket": "セカンダリーマーケット",
  "summary.releaseWithdraw": "リリースと引き出し",
  "summary.dynamicRewards": "動的報酬",
  "summary.totalInvestment": "総投資",
  "summary.netProfit": "純利益",
  "summary.totalReturns": "総収益",
  "summary.totalTax": "総税金",
  "summary.tierAndPerformance": "ティア + パフォーマンス",
  "summary.noData": "以下のタブで計算を完了すると、サマリーが表示されます",
  "summary.investment": "投資",
  "summary.profit": "利益",
  "summary.tax": "税金",

  "simulator.title": "キャッシュフローシミュレーター",
  "simulator.desc": "資金保護を備えたトレジャリーキャッシュフローの日次シミュレーション",

  "footer.chain": "Base チェーン",
  "footer.totalSupply": "総供給量",
  "footer.initialCirculation": "初期流通量",
  "footer.deliveryContract": "デリバリーコントラクト",
  "footer.title": "B18 トークンエコノミクス計算機",
  "footer.stats": "Base チェーン | 合計: 10.1M | 初期: 100K | デリバリー: 10M",

  "common.day": "日",
  "common.days": "日",
  "common.month": "月",
  "common.year": "年",
  "common.daily": "日次",
  "common.monthly": "月次",
  "common.annual": "年次",
  "common.total": "合計",
  "common.net": "純",
  "common.gross": "総",
  "common.rate": "率",
  "common.amount": "金額",
  "common.tokens": "トークン",
  "common.price": "価格",
  "common.value": "価値",
  "common.balance": "残高",
  "common.status": "ステータス",
  "common.times30": "x30",
  "common.times360": "x360",
};

const th: Dict = {
  "app.title": "B18 เศรษฐศาสตร์โทเค็น",
  "app.subtitle": "เครื่องคำนวณโปรโตคอล DeFi",
  "button.reset": "รีเซ็ต",
  "button.resetAll": "รีเซ็ตข้อมูลทั้งหมด",
  "button.calculate": "คำนวณ",
  "button.confirm": "ยืนยัน",
  "button.cancel": "ยกเลิก",
  "button.add": "เพิ่ม",
  "button.remove": "ลบ",

  "metrics.price": "ราคา B18",
  "metrics.circulation": "การหมุนเวียน",
  "metrics.treasury": "คลัง",
  "metrics.burned": "เผาแล้ว",
  "metrics.delivery": "สัญญาส่งมอบ",
  "metrics.lpUsdt": "LP USDC",
  "metrics.lpB18": "LP B18",
  "metrics.fromDelivery": "จากสัญญาส่งมอบ",
  "metrics.bonusPool": "พูลโบนัส",

  "tab.staking": "สเตกพรีเซล",
  "tab.secondary": "ตลาดรอง",
  "tab.release": "ปลดและถอน",
  "tab.rewards": "รางวัลแบบไดนามิก",
  "tab.distribution": "การกระจายโทเค็น",
  "tab.summary": "สรุป",
  "tab.simulator": "จำลองกระแสเงินสด",
  "tabs.staking": "สเตก",
  "tabs.secondary": "ตลาด",
  "tabs.release": "ปลด",
  "tabs.rewards": "รางวัล",
  "tabs.distribution": "การกระจาย",
  "tabs.summary": "สรุป",
  "tabs.simulator": "กระแสเงินสด",

  "staking.title": "เครื่องคำนวณสเตกพรีเซล",
  "staking.desc": "ซื้อพรีเซลโดยไม่มีสลิปเพจ แบ่ง USDC: 50% ไปคลัง, 50% ไป LP สัญญาส่งมอบจะเพิ่ม B18 จำนวนเท่ากันใน LP เพื่อรักษาเสถียรภาพราคา โทเค็นจะถูกปลดรายวันหลังการสเตก",
  "staking.params": "พารามิเตอร์การลงทุน",
  "staking.amount": "จำนวนลงทุน (USDC ขั้นต่ำ 100)",
  "staking.period": "ระยะเวลาสเตก",
  "staking.releasePeriod": "ระยะเวลาปลด",
  "staking.compound": "ทบต้นรายวัน",
  "staking.compoundDesc": "เปิดใช้การทบต้น: เงินต้น + ดอกเบี้ยรายวัน = เงินต้นวันถัดไป",
  "staking.flow": "ขั้นตอนการลงทุน",
  "staking.fundFlow": "กระแสเงิน (ไม่มีสลิปเพจ)",
  "staking.toTreasury": "เข้าคลัง",
  "staking.toLP": "เข้าพูล LP",
  "staking.deliveryLP": "สัญญาส่งมอบเพิ่มไปยัง LP",
  "staking.lpMatch": "จับคู่ 50% USDC รักษาเสถียรภาพราคา",
  "staking.priceImpact": "ผลกระทบต่อราคา",
  "staking.priceStable": "ราคาคงที่",
  "staking.priceStableDesc": "สัญญาส่งมอบเพิ่ม B18 จำนวนเท่ากันใน LP, USDC และ B18 เพิ่มตามสัดส่วน ราคาจึงคงที่",
  "staking.returns": "ผลตอบแทนการลงทุน",
  "staking.tokensReceived": "โทเค็นที่ได้รับ",
  "staking.stakingReturns": "ผลตอบแทนสเตก",
  "staking.totalReturn": "ดอกเบี้ยทั้งหมด",
  "staking.releaseTax": "ภาษีปลด",
  "staking.totalPeriod": "ระยะเวลาทั้งหมด",
  "staking.days": "วัน",
  "staking.principal": "เงินต้น",
  "staking.noSlippage": "พรีเซลไม่มีสลิปเพจ",
  "staking.stakingPL": "กำไรขาดทุนสเตก",
  "staking.dailyProfit": "กำไรรายวัน",
  "staking.netProfit": "กำไรสุทธิ",
  "staking.simulate": "จำลองการซื้อและสเตก",
  "staking.details": "รายละเอียด",

  "secondary.title": "การซื้อขายตลาดรอง",
  "secondary.desc": "การซื้อขาย AMM พร้อมค่าสลิปเพจ 3%, 60% เข้าคลัง, 20% เผา, 20% เข้าพูลโบนัส",
  "secondary.buy": "ซื้อ",
  "secondary.sell": "ขาย",
  "secondary.buyAmount": "จำนวนซื้อ (USDC)",
  "secondary.sellAmount": "จำนวนขาย (B18)",
  "secondary.priceInfo": "ข้อมูลราคา",
  "secondary.currentPrice": "ราคาปัจจุบัน",
  "secondary.afterPrice": "ราคาหลังซื้อขาย",
  "secondary.slippage": "สลิปเพจ",
  "secondary.slippageFee": "ค่าสลิปเพจ",
  "secondary.feeDistribution": "การแบ่งค่าธรรมเนียม",
  "secondary.toTreasury": "เข้าคลัง",
  "secondary.toBurn": "เผา",
  "secondary.toBonus": "เข้าพูลโบนัส",
  "secondary.tradeResult": "ผลการซื้อขาย",
  "secondary.tokensReceived": "โทเค็นที่ได้รับ",
  "secondary.usdtReceived": "USDC ที่ได้รับ",
  "secondary.simulateBuy": "จำลองการซื้อ",
  "secondary.simulateSell": "จำลองการขาย",

  "release.title": "ปลดและถอน",
  "release.desc": "ปลดโทเค็นที่สเตกเพื่อรับ USDC คลังจ่ายเป็น USDC, B18 ที่ปลดจะถูกกระจาย: 60% ไปสัญญาส่งมอบ, 20% เผา, 20% พูลโบนัส",
  "release.simulator": "เครื่องจำลองการปลดและถอน",
  "release.stakedTokens": "โทเค็นที่สเตก (จากเครื่องคำนวณสเตก)",
  "release.stakedAmount": "จำนวนที่สเตก (ต้น+ดอก)",
  "release.releasePeriod": "ระยะเวลาปลด",
  "release.releaseResult": "ผลการปลด",
  "release.dailyRelease": "ปลดรายวัน",
  "release.monthlyRelease": "ปลดรายเดือน",
  "release.totalRelease": "ปลดทั้งหมด",
  "release.releaseTax": "ภาษีปลด",
  "release.netRelease": "ปลดสุทธิ",
  "release.withdrawalPayout": "การจ่ายถอน",
  "release.b18Distribution": "การกระจาย B18 หลังจ่าย",
  "release.toDelivery": "ไปสัญญาส่งมอบ",
  "release.toBurn": "เผา (หลุมดำ)",
  "release.toBonus": "พูลโบนัส",
  "release.simulateRelease": "จำลองการปลด",
  "release.params": "พารามิเตอร์การปลด",
  "release.withdrawDays": "วันถอน",
  "release.simulationDay": "วันจำลอง",
  "release.calculateDay": "คำนวณวัน",
  "release.dayStatus": "สถานะวัน",
  "release.treasuryBalance": "ยอดคลัง",
  "release.currentPrice": "ราคาปัจจุบัน",
  "release.preview": "ตัวอย่างการปลด",
  "release.taxAmount": "จำนวนภาษี",
  "release.taxRate": "อัตราภาษี",
  "release.taxB18": "ภาษี B18",
  "release.taxUsdt": "มูลค่าภาษี USDC",
  "release.taxBuyback": "ผลกระทบจากภาษีการซื้อคืน",
  "release.confirmRelease": "ยืนยันการปลด",
  "release.cashflow": "สถานะกระแสเงินสด",
  "release.sufficient": "เพียงพอ",
  "release.insufficient": "ไม่เพียงพอ",
  "release.queueRequired": "ต้องเข้าคิว",
  "release.dayPayout": "ต้องจ่ายในวันนั้น",

  "rewards.title": "เครื่องคำนวณรางวัลแบบไดนามิก",
  "rewards.desc": "รางวัลสะสมระดับ V1-V10 ตามผลงานของทีม",
  "rewards.tierTab": "รางวัลระดับ",
  "rewards.layerTab": "รางวัลผลงาน",
  "rewards.memberTier": "ระดับสมาชิก",
  "rewards.qualifyingRange": "ช่วงคุณสมบัติ",
  "rewards.teamPerformance": "ผลงานทีม (10K USDC)",
  "rewards.currentTier": "ระดับปัจจุบัน",
  "rewards.rewardRate": "อัตรารางวัล",
  "rewards.grossReward": "รางวัลรวม",
  "rewards.releaseTax": "ภาษีปลด",
  "rewards.netReward": "รางวัลสุทธิ",
  "rewards.rewardFormula": "สูตรรางวัล",
  "rewards.performanceTokens": "โทเค็นผลงาน",
  "rewards.baseReward": "รางวัลพื้นฐาน",
  "rewards.tierReward": "รางวัลระดับ",
  "rewards.taxPurchase": "ต้องซื้อภาษี",
  "rewards.treasuryPays": "คลังจ่าย",
  "rewards.taxDistribution": "การกระจายภาษี B18",
  "rewards.dailyReward": "รางวัลรายวัน",
  "rewards.monthlyReward": "รางวัลรายเดือน",
  "rewards.annualReward": "รางวัลรายปี",
  "rewards.layerNumber": "ชั้น",
  "rewards.layerPerformance": "ผลงานชั้น",
  "rewards.layerPercent": "เปอร์เซ็นต์ชั้น",
  "rewards.layerReward": "รางวัลชั้น",
  "rewards.networkPerformance": "ผลงานเครือข่าย",
  "rewards.totalLayers": "ชั้นทั้งหมด",
  "rewards.addLayer": "เพิ่มชั้น",
  "rewards.bonusPool": "พูลโบนัส",
  "rewards.performanceRatio": "อัตราส่วนผลงาน",
  "rewards.totalPerformance": "ผลงานรวม",
  "rewards.totalReward": "รางวัลรวม",
  "rewards.warning": "คำเตือน",
  "rewards.exceedsNetwork": "ผลรวมเกินผลงานเครือข่าย",

  "distribution.title": "การกระจายโทเค็น",
  "distribution.circulation": "การหมุนเวียน",
  "distribution.delivery": "สัญญาส่งมอบ",
  "distribution.burned": "เผาแล้ว",
  "distribution.bonusPool": "พูลโบนัส",
  "distribution.lpPool": "พูล LP",

  "summary.title": "สรุปการคำนวณ",
  "summary.stakingInput": "ป้อนข้อมูลสเตก",
  "summary.secondaryMarket": "ตลาดรอง",
  "summary.releaseWithdraw": "ปลดและถอน",
  "summary.dynamicRewards": "รางวัลแบบไดนามิก",
  "summary.totalInvestment": "เงินลงทุนรวม",
  "summary.netProfit": "กำไรสุทธิ",
  "summary.totalReturns": "ผลตอบแทนรวม",
  "summary.totalTax": "ภาษีรวม",
  "summary.tierAndPerformance": "ระดับ + ผลงาน",
  "summary.noData": "ทำการคำนวณในแท็บด้านล่างเพื่อดูสรุป",
  "summary.investment": "การลงทุน",
  "summary.profit": "กำไร",
  "summary.tax": "ภาษี",

  "simulator.title": "จำลองกระแสเงินสด",
  "simulator.desc": "การจำลองกระแสเงินสดของคลังรายวันพร้อมการป้องกันเงินทุน",

  "footer.chain": "Base Chain",
  "footer.totalSupply": "อุปทานทั้งหมด",
  "footer.initialCirculation": "การหมุนเวียนเริ่มต้น",
  "footer.deliveryContract": "สัญญาส่งมอบ",
  "footer.title": "เครื่องคำนวณเศรษฐศาสตร์โทเค็น B18",
  "footer.stats": "Base Chain | ทั้งหมด: 10.1M | เริ่มต้น: 100K | ส่งมอบ: 10M",

  "common.day": "วัน",
  "common.days": "วัน",
  "common.month": "เดือน",
  "common.year": "ปี",
  "common.daily": "รายวัน",
  "common.monthly": "รายเดือน",
  "common.annual": "รายปี",
  "common.total": "รวม",
  "common.net": "สุทธิ",
  "common.gross": "รวม",
  "common.rate": "อัตรา",
  "common.amount": "จำนวน",
  "common.tokens": "โทเค็น",
  "common.price": "ราคา",
  "common.value": "มูลค่า",
  "common.balance": "ยอดคงเหลือ",
  "common.status": "สถานะ",
  "common.times30": "x30",
  "common.times360": "x360",
};

const vi: Dict = {
  "app.title": "Kinh tế Token B18",
  "app.subtitle": "Máy tính Giao thức DeFi",
  "button.reset": "Đặt lại",
  "button.resetAll": "Đặt lại tất cả dữ liệu",
  "button.calculate": "Tính toán",
  "button.confirm": "Xác nhận",
  "button.cancel": "Hủy",
  "button.add": "Thêm",
  "button.remove": "Xóa",

  "metrics.price": "Giá B18",
  "metrics.circulation": "Lưu thông",
  "metrics.treasury": "Kho bạc",
  "metrics.burned": "Đã đốt",
  "metrics.delivery": "Hợp đồng Phân phối",
  "metrics.lpUsdt": "LP USDC",
  "metrics.lpB18": "LP B18",
  "metrics.fromDelivery": "Từ Phân phối",
  "metrics.bonusPool": "Quỹ thưởng",

  "tab.staking": "Stake Presale",
  "tab.secondary": "Thị trường Thứ cấp",
  "tab.release": "Giải phóng & Rút",
  "tab.rewards": "Phần thưởng Động",
  "tab.distribution": "Phân phối Token",
  "tab.summary": "Tóm tắt",
  "tab.simulator": "Mô phỏng Dòng tiền",
  "tabs.staking": "Stake",
  "tabs.secondary": "Thị trường",
  "tabs.release": "Giải phóng",
  "tabs.rewards": "Thưởng",
  "tabs.distribution": "Phân phối",
  "tabs.summary": "Tóm tắt",
  "tabs.simulator": "Dòng tiền",

  "staking.title": "Máy tính Stake Presale",
  "staking.desc": "Mua presale không trượt giá, USDC chia: 50% vào kho bạc, 50% vào LP. Hợp đồng Phân phối thêm B18 tương ứng vào LP để duy trì ổn định giá. Token được giải phóng hàng ngày sau khi stake.",
  "staking.params": "Tham số Đầu tư",
  "staking.amount": "Số tiền Đầu tư (USDC, tối thiểu 100)",
  "staking.period": "Thời gian Stake",
  "staking.releasePeriod": "Thời gian Giải phóng",
  "staking.compound": "Gộp lãi Hàng ngày",
  "staking.compoundDesc": "Bật gộp lãi: gốc + lãi hàng ngày = gốc ngày hôm sau",
  "staking.flow": "Quy trình Đầu tư",
  "staking.fundFlow": "Dòng vốn (Không trượt giá)",
  "staking.toTreasury": "Vào Kho bạc",
  "staking.toLP": "Vào Quỹ LP",
  "staking.deliveryLP": "Hợp đồng Phân phối thêm vào LP",
  "staking.lpMatch": "Khớp 50% USDC, duy trì ổn định giá",
  "staking.priceImpact": "Ảnh hưởng Giá",
  "staking.priceStable": "Giá Ổn định",
  "staking.priceStableDesc": "Hợp đồng Phân phối thêm B18 tương ứng vào LP, USDC và B18 tăng theo tỷ lệ, giá giữ ổn định",
  "staking.returns": "Lợi nhuận Đầu tư",
  "staking.tokensReceived": "Token Nhận được",
  "staking.stakingReturns": "Lợi nhuận Stake",
  "staking.totalReturn": "Tổng Lãi",
  "staking.releaseTax": "Thuế Giải phóng",
  "staking.totalPeriod": "Tổng Thời gian",
  "staking.days": "ngày",
  "staking.principal": "Vốn gốc",
  "staking.noSlippage": "Presale Không Trượt giá",
  "staking.stakingPL": "Lãi/Lỗ Stake",
  "staking.dailyProfit": "Lợi nhuận Hàng ngày",
  "staking.netProfit": "Lợi nhuận Ròng",
  "staking.simulate": "Mô phỏng Mua & Stake",
  "staking.details": "Chi tiết",

  "secondary.title": "Giao dịch Thị trường Thứ cấp",
  "secondary.desc": "Giao dịch AMM với phí trượt giá 3%, 60% vào kho bạc, 20% đốt, 20% vào quỹ thưởng",
  "secondary.buy": "Mua",
  "secondary.sell": "Bán",
  "secondary.buyAmount": "Số tiền Mua (USDC)",
  "secondary.sellAmount": "Số lượng Bán (B18)",
  "secondary.priceInfo": "Thông tin Giá",
  "secondary.currentPrice": "Giá Hiện tại",
  "secondary.afterPrice": "Giá Sau Giao dịch",
  "secondary.slippage": "Trượt giá",
  "secondary.slippageFee": "Phí Trượt giá",
  "secondary.feeDistribution": "Phân phối Phí",
  "secondary.toTreasury": "Vào Kho bạc",
  "secondary.toBurn": "Đốt",
  "secondary.toBonus": "Vào Quỹ thưởng",
  "secondary.tradeResult": "Kết quả Giao dịch",
  "secondary.tokensReceived": "Token Nhận được",
  "secondary.usdtReceived": "USDC Nhận được",
  "secondary.simulateBuy": "Mô phỏng Mua",
  "secondary.simulateSell": "Mô phỏng Bán",

  "release.title": "Giải phóng & Rút",
  "release.desc": "Giải phóng token đã stake để lấy USDC. Kho bạc trả bằng USDC, B18 đã giải phóng phân phối: 60% vào hợp đồng phân phối, 20% đốt, 20% quỹ thưởng.",
  "release.simulator": "Mô phỏng Giải phóng Rút",
  "release.stakedTokens": "Token đã Stake (từ máy tính stake)",
  "release.stakedAmount": "Số lượng đã Stake (G+L)",
  "release.releasePeriod": "Thời gian Giải phóng",
  "release.releaseResult": "Kết quả Giải phóng",
  "release.dailyRelease": "Giải phóng Hàng ngày",
  "release.monthlyRelease": "Giải phóng Hàng tháng",
  "release.totalRelease": "Tổng Giải phóng",
  "release.releaseTax": "Thuế Giải phóng",
  "release.netRelease": "Giải phóng Ròng",
  "release.withdrawalPayout": "Chi trả Rút",
  "release.b18Distribution": "Phân phối B18 Sau Chi trả",
  "release.toDelivery": "Vào Hợp đồng Phân phối",
  "release.toBurn": "Đốt (Hố đen)",
  "release.toBonus": "Quỹ thưởng",
  "release.simulateRelease": "Mô phỏng Giải phóng",
  "release.params": "Tham số Giải phóng",
  "release.withdrawDays": "Số ngày Rút",
  "release.simulationDay": "Ngày Mô phỏng",
  "release.calculateDay": "Tính Ngày",
  "release.dayStatus": "Trạng thái Ngày",
  "release.treasuryBalance": "Số dư Kho bạc",
  "release.currentPrice": "Giá Hiện tại",
  "release.preview": "Xem trước Giải phóng",
  "release.taxAmount": "Số tiền Thuế",
  "release.taxRate": "Tỷ lệ Thuế",
  "release.taxB18": "Thuế B18",
  "release.taxUsdt": "Giá trị Thuế USDC",
  "release.taxBuyback": "Tác động Mua lại Thuế",
  "release.confirmRelease": "Xác nhận Giải phóng",
  "release.cashflow": "Trạng thái Dòng tiền",
  "release.sufficient": "Đủ",
  "release.insufficient": "Không đủ",
  "release.queueRequired": "Cần Xếp hàng",
  "release.dayPayout": "Cần Chi trả Ngày",

  "rewards.title": "Máy tính Phần thưởng Động",
  "rewards.desc": "Phần thưởng tích lũy cấp V1-V10 dựa trên hiệu suất đội",
  "rewards.tierTab": "Phần thưởng Cấp",
  "rewards.layerTab": "Phần thưởng Hiệu suất",
  "rewards.memberTier": "Cấp Thành viên",
  "rewards.qualifyingRange": "Phạm vi Đủ điều kiện",
  "rewards.teamPerformance": "Hiệu suất Đội (10K USDC)",
  "rewards.currentTier": "Cấp Hiện tại",
  "rewards.rewardRate": "Tỷ lệ Thưởng",
  "rewards.grossReward": "Thưởng Gộp",
  "rewards.releaseTax": "Thuế Giải phóng",
  "rewards.netReward": "Thưởng Ròng",
  "rewards.rewardFormula": "Công thức Thưởng",
  "rewards.performanceTokens": "Token Hiệu suất",
  "rewards.baseReward": "Thưởng Cơ bản",
  "rewards.tierReward": "Thưởng Cấp",
  "rewards.taxPurchase": "Cần Mua Thuế",
  "rewards.treasuryPays": "Kho bạc Trả",
  "rewards.taxDistribution": "Phân phối Thuế B18",
  "rewards.dailyReward": "Thưởng Hàng ngày",
  "rewards.monthlyReward": "Thưởng Hàng tháng",
  "rewards.annualReward": "Thưởng Hàng năm",
  "rewards.layerNumber": "Tầng",
  "rewards.layerPerformance": "Hiệu suất Tầng",
  "rewards.layerPercent": "Tỷ lệ Tầng",
  "rewards.layerReward": "Thưởng Tầng",
  "rewards.networkPerformance": "Hiệu suất Mạng",
  "rewards.totalLayers": "Tổng Tầng",
  "rewards.addLayer": "Thêm Tầng",
  "rewards.bonusPool": "Quỹ thưởng",
  "rewards.performanceRatio": "Tỷ lệ Hiệu suất",
  "rewards.totalPerformance": "Tổng Hiệu suất",
  "rewards.totalReward": "Tổng Thưởng",
  "rewards.warning": "Cảnh báo",
  "rewards.exceedsNetwork": "Tổng vượt quá hiệu suất mạng",

  "distribution.title": "Phân phối Token",
  "distribution.circulation": "Lưu thông",
  "distribution.delivery": "Hợp đồng Phân phối",
  "distribution.burned": "Đã đốt",
  "distribution.bonusPool": "Quỹ thưởng",
  "distribution.lpPool": "Quỹ LP",

  "summary.title": "Tóm tắt Tính toán",
  "summary.stakingInput": "Đầu vào Stake",
  "summary.secondaryMarket": "Thị trường Thứ cấp",
  "summary.releaseWithdraw": "Giải phóng & Rút",
  "summary.dynamicRewards": "Phần thưởng Động",
  "summary.totalInvestment": "Tổng Đầu tư",
  "summary.netProfit": "Lợi nhuận Ròng",
  "summary.totalReturns": "Tổng Lợi nhuận",
  "summary.totalTax": "Tổng Thuế",
  "summary.tierAndPerformance": "Cấp + Hiệu suất",
  "summary.noData": "Hoàn thành tính toán ở các tab bên dưới để xem tóm tắt",
  "summary.investment": "Đầu tư",
  "summary.profit": "Lợi nhuận",
  "summary.tax": "Thuế",

  "simulator.title": "Mô phỏng Dòng tiền",
  "simulator.desc": "Mô phỏng dòng tiền kho bạc hàng ngày với bảo vệ vốn",

  "footer.chain": "Base Chain",
  "footer.totalSupply": "Tổng Cung",
  "footer.initialCirculation": "Lưu thông Ban đầu",
  "footer.deliveryContract": "Hợp đồng Phân phối",
  "footer.title": "Máy tính Kinh tế Token B18",
  "footer.stats": "Base Chain | Tổng: 10.1M | Ban đầu: 100K | Phân phối: 10M",

  "common.day": "ngày",
  "common.days": "ngày",
  "common.month": "tháng",
  "common.year": "năm",
  "common.daily": "Hàng ngày",
  "common.monthly": "Hàng tháng",
  "common.annual": "Hàng năm",
  "common.total": "Tổng",
  "common.net": "Ròng",
  "common.gross": "Gộp",
  "common.rate": "Tỷ lệ",
  "common.amount": "Số tiền",
  "common.tokens": "Token",
  "common.price": "Giá",
  "common.value": "Giá trị",
  "common.balance": "Số dư",
  "common.status": "Trạng thái",
  "common.times30": "x30",
  "common.times360": "x360",
};

const dictionaries: Record<Language, Dict> = {
  en,
  zh,
  "zh-TW": zhTW,
  ko,
  ja,
  th,
  vi,
};

const STORAGE_KEY = "b18-language";

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") return "zh";
    const stored = window.localStorage.getItem(STORAGE_KEY) as Language | null;
    if (stored && stored in dictionaries) return stored;
    return "zh";
  });

  useEffect(() => {
    if (typeof window !== "undefined") {
      window.localStorage.setItem(STORAGE_KEY, language);
    }
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
  }, []);

  const toggleLanguage = useCallback(() => {
    setLanguageState((prev) => (prev === "en" ? "zh" : "en"));
  }, []);

  const t = useCallback(
    (key: string): string => {
      const dict = dictionaries[language];
      if (dict && dict[key] !== undefined) return dict[key];
      if (en[key] !== undefined) return en[key];
      console.warn(`Missing translation for key: ${key}`);
      return key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
